name: Run tests

on:
  push:
  pull_request:
  schedule:
    # run every Tuesday at 5am UTC
    - cron: '0 5 * * 2'

jobs:
  tests:
    name: ${{ matrix.name}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.9
            name: Py3.9 mindeps
            toxenv: py39-test
          - os: ubuntu-latest
            python-version: '3.10'
            name: Py3.10 mindeps
            toxenv: py310-test
          - os: ubuntu-latest
            python-version: 3.11
            name: Py3.11 mindeps
            toxenv: py311-test
          - os: ubuntu-latest
            python-version: 3.8
            name: Py3.8 mindeps
            toxenv: py38-test
          - os: ubuntu-latest
            python-version: 3.9
            name: Py3.9 dev
            toxenv: py39-test-dev
          - os: ubuntu-latest
            python-version: 3.11
            name: Py3.11 dev
            toxenv: py311-test-dev
          - os: ubuntu-latest
            python-version: 3.9
            name: Documentation
            toxenv: build_docs

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install testing dependencies
      run: python -m pip install tox codecov
    - name: Run tests with ${{ matrix.name }}
      run: tox -v -e ${{ matrix.toxenv }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
